jupiter-controller-update: confirm firmware file(s)
Currently we don't validate that the firmware file(s) are present. As
result, if a firmware update is needed although the file is not there
(like on my EV2 unit), we'll trigger the update process only to error
out.

This get particularly messy with the upcoming wrapper, which will
ensure plymouth is running as needed. Without this change we'll start
plymouth, start drawing the progress and exit midway.

Signed-off-by: Emil Velikov <emil.velikov@collabora.com>

diff --git a/usr/bin/jupiter-controller-update b/usr/bin/jupiter-controller-update
--- a/usr/bin/jupiter-controller-update
+++ b/usr/bin/jupiter-controller-update
@@ -209,6 +209,27 @@ fi
 
 info "Found candidate device, build timestamp ${build_timestamp:-unknown}, BL $bootloader, BL_Type $major_release, HYB ${hybrid}"
 
+check_firmware() {
+  if ! [[ -f "$1" ]]; then
+     die "Required firmware file $1 is missing"
+  fi
+}
+
+if [[ ${bootloader_type} -eq 1 ]]; then
+  check_firmware "$CURRENT_FW_FILE_D21"
+elif [[ ${bootloader_type} -eq 2 ]]; then
+  if [[ $hybrid = "true" ]]; then
+    check_firmware "$CURRENT_FW_FILE_D20"
+  else
+    check_firmware "$CURRENT_FW_FILE_D21"
+  fi
+  check_firmware "$CURRENT_FW_FILE_D21"
+elif [[ ${bootloader_type} -eq 3 ]]; then
+  check_firmware "$CURRENT_FW_FILE_RA4"
+else
+  die "Unknown Bootloader Type"
+fi
+
 # Done if check mode
 if [[ -n $checkmode ]]; then
   info "  --check specified, not performing update"
