Ensure we handle cases where sys/class/dmi isn't readable
These nodes can simply not exist, handle the no-read case explicitly.

jupiter-controller-update may slightly change behavior here, in that
it will not attempt to function on devices without a serial.  That is
rather unexpected, so being conservative here makes sense.

diff --git a/usr/bin/jupiter-controller-update b/usr/bin/jupiter-controller-update
--- a/usr/bin/jupiter-controller-update
+++ b/usr/bin/jupiter-controller-update
@@ -15,7 +15,7 @@ is_steamdeck() {
 # Is this an EV2 or older unit
 is_ev2() {
   local product_serial
-  product_serial="$(cat /sys/devices/virtual/dmi/id/product_serial)"
+  product_serial="$(cat /sys/devices/virtual/dmi/id/product_serial)" || die "Cannot check device serial"
   local product_year="${product_serial:4:1}"
   local product_week="${product_serial:5:2}"
 
