automount: don't use DEVICE on make_dbus_udisks_call()
This is a global variable that is only used for reporting errors.
Use the 'object' parameter rather than relying on the existence of a
global variable.

diff --git a/usr/lib/hwsupport/common-functions b/usr/lib/hwsupport/common-functions
--- a/usr/lib/hwsupport/common-functions
+++ b/usr/lib/hwsupport/common-functions
@@ -17,14 +17,14 @@ make_dbus_udisks_call()
                "org.freedesktop.UDisks2.${iface}" "${method}" "$@") || ret=$?
 
     if [[ $ret -ne 0 ]]; then
-        echo "Error running ${cmd} ${method} on ${DEVICE} (status = $ret)" >&2
+        echo "Error running ${cmd} ${method} on ${object} (status = $ret)" >&2
         exit 1
     fi
 
     # Expected reply must be of ${type} contain ${field}: value
     ret=$(jq -r "if .${field} != null and .type == \"${type}\" then .${field} else \"\" end" <<< "$reply" || true)
     if [[ -z $ret ]]; then
-        echo "Error when running '${cmd} ${method}' on ${DEVICE}: udisks returned success but could not parse reply:" >&2
+        echo "Error when running '${cmd} ${method}' on ${object}: udisks returned success but could not parse reply:" >&2
         echo "---"$'\n'"$reply"$'\n'"---" >&2
         exit 1
     fi
